# File: azure-pipelines.yml
trigger:
 branches:
    include:
      - main
      - v*/beta
pr: none
stages:
- stage: Build
  displayName: 'Build'
  jobs:
  - template: ../Actions/build.yml
    parameters:
      agentPool: "Azure Pipelines"
      PackageSuffix: "Beta"
- stage: Deploy
  displayName: 'Deploy'
  jobs:
  - template: ../Actions/deploy.yml
    parameters:
      agentPool: "Azure Pipelines"
      nugetFeed: "NuGet"
