# File: azure-pipelines.yml
trigger: none 
pr: 
- '*'
stages:
- stage: Build
  displayName: 'Build'
  jobs:
  - template: ../Actions/build.yml
    parameters:
      agentPool: "Azure Pipelines"
      PackageSuffix: "Pr"
- stage: Analyse
  displayName: 'Analyse'
  jobs:
  - template: ../Actions/analise.yml    
    parameters:
      agentPool: "Azure Pipelines"
