# File: azure-pipelines.yml
trigger:
 branches:
    include:
      - '*'
stages:
  - stage: Build
    displayName: 'Build'
    jobs:
      - template: ../Actions/build.yml
  - stage: Analyse
    displayName: 'Analyse'
    jobs:
      - template: ../Actions/analise.yml    
