# File: azure-pipelines.yml
trigger:
 branches:
    include:
      - '*'
stages:
- stage: Build
  displayName: 'Build'
  jobs:
  - template: ../Actions/build.yml
    parameters:
      agentPool: "Azure Pipelines"
- stage: Analyse
  displayName: 'Analyse'
  jobs:
  - template: ../Actions/analise.yml    
    parameters:
      agentPool: "Azure Pipelines"
