- stage: deploy
  displayName: Stable Deployment
  pool: 
    name: '${{parameters.agentPool}}'
    demands:
      Agent.OS -equals Windows_NT
  dependsOn: build
  jobs:
  - job: Deploy
    pool: 
      name: '${{parameters.agentPool}}'
      demands:
        Agent.OS -equals Windows_NT
    steps:
    - task: DeleteFiles@1
      inputs:
        SourceFolder: '$(Pipeline.Workspace)/publish artifacts/'
        Contents: '**/*'
        RemoveSourceFolder: true
    - download: current
      artifact: 'publish artifacts'
    - task: NuGetToolInstaller@1
    - template: ../push.yml
      parameters:
         NugetFeedCredentials: '${{parameters.nugetFeed}}'
    - template: ../push.yml
      parameters:
        NugetFeedCredentials: '${{parameters.secondNugetFeed}}'